/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rws4l_000' at '31.10.17 15:40' with Gradle 3.0
 *
 * @author rws4l_000, @date 31.10.17 15:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
